name: LoanDataApp
description: A Flutter project for rendering loan data from a given schema

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter  
  flutter_bloc: ^6.0.0
  http: ^0.12.0
  equatable: ^1.2.0
  json_to_model: ^1.3.13
  build_runner: ^1.7.4
  json_serializable: ^3.2.5
  json_annotation: ^3.0.1
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/